const actionType = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCSESS: 'REGISTER_SUCCSESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_GOOGLE: 'LOGIN_GOOGLE',
    LOGIN_FACEBOOK: 'LOGIN_FACEBOOK',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    GET_CURRENT: 'GET_CURRENT',
    GET_ALL_USER: 'GET_ALL_USER',
    DELETE_USER: 'DELETE_USER',
    UPDTAE_USER: 'UPDTAE_USER'
}

export default actionType